### PR TITLE
fix(vue-renderless): [autocomplete,base-select,amount,anchor,area] fix site: Optimize site documentation typesetting

### PR DESCRIPTION
**Pull request by dufu1991**
# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-vue/blob/dev/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **New Features**
	- Added spaces between words in various scenario labels and option values for improved readability across multiple components.

- **Bug Fixes**
	- Updated expected values in tests to match new formatting with spaces in option names and scenario labels.

- **Documentation**
	- Improved comments in test cases for clarity regarding formatting changes.

### CODE REVIEW

**Comment by zzcr** [comment]
你好，感谢您的mr，有两个E2E测试用例没有过哈~~麻烦看一下

**Comment by dufu1991** [comment]
> 你好，感谢您的mr，有两个E2E测试用例没有过哈~~麻烦看一下

有些文案中文和动态数字组合的时候没有加空格，但是文案加了就过不了。比如 北京${index} ，实际文案是 北京 1，中间这个空格就不好处理，会有遗漏。

**Comment by dufu1991** [comment]
@zzcr 我看测试没过，这个 API 浏览器中有，Node 环境中好像没有吧，不是很懂。

**Comment by zzcr** [comment]
那个是单元测试，我们新加的git-actions，这个不要紧，不是你修改带来的

**Comment by dufu1991** [comment]
@all-contributors please add @dufu1991 for <contributions>

**Comment by dufu1991** [comment]
@all-contributors please add @dufu1991 for doc.

**Pull request merged**
