### PR TITLE
test(modal): add modal unit test

### PR DESCRIPTION
**Pull request by Zz-ZzzZ**
# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-vue/blob/dev/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] Other... Please describe: add unit test

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by Zz-ZzzZ** [comment]
这个resize的单元测试我不知道怎么触发，如果有知道方法的可以告诉我一下

**Comment by kagol** [comment]
@Zz-ZzzZ 你看下这个对你有帮助吗？https://stackoverflow.com/questions/52831676/how-to-test-drag-and-drop-with-vue-and-jest

**Comment by Zz-ZzzZ** [comment]
@kagol 我下周来试试，没想到用drag事件来模拟🤣

**Comment by kagol** [comment]
@Zz-ZzzZ 记得处理下冲突

**Comment by Zz-ZzzZ** [comment]
@kagol 原本的代码缩进不对，这里的冲突是我用Prettier格式化后的代码，接受我的就行，modal还剩两个todo没完成，那里有个bug，刚打开弹窗时不会按照设置的min-width/min-height正确设置，后面修复了我在把这个测试补上

**Review by zzcr — DISMISSED** [review]

**Comment by zzcr** [comment]
@Zz-ZzzZ 代码有冲突合并不了~~ 记得解决下冲突哈~

**Comment by Zz-ZzzZ** [comment]
@zzcr 那个格式有问题我用Prettier格式化了一下，不能选择我的代码覆盖吗

**Comment by Zz-ZzzZ** [comment]
@zzcr 冲突已解决~请查看

**Review by kagol — APPROVED** [review]

**Pull request merged**
