### PR TITLE
feat(ci): add pr preview action

### PR DESCRIPTION
**Pull request by mengqiuleo**
# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-vue/blob/dev/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by mengqiuleo** [comment]
增加 pr 预览

**Comment by kagol** [comment]
@mengqiuleo 我看提交了多个无关的文件，比如 aurora-theme/component.js等，这几个文件是开发态的，不需要提交

**Comment by mengqiuleo** [comment]
> @mengqiuleo 我看提交了多个无关的文件，比如 aurora-theme/component.js等，这几个文件是开发态的，不需要提交

不提交 build site  会报错，https://github.com/opentiny/tiny-vue/actions/runs/7677252006/job/20925758270，

Snipaste_2024-01-28_09-22-47

@kagol

**Comment by mengqiuleo** [comment]
在 build 时动态生成 component.js : `fs.writeFileSync(packages/theme/src/theme/${themeKey}/component.js, contents)`

并且 在 aurora-theme/index.js 中引入，https://github.com/opentiny/tiny-vue/blob/dev/packages/theme/src/theme/aurora-theme/index.js#L561

但是 github action 读不到

**Comment by mengqiuleo** [comment]
`need help`: 我在本地的一个干净分支上执行 build:inner:alpha  也会报错：
Snipaste_2024-01-28_09-22-47

**Comment by mengqiuleo** [comment]
好像只有 build:theme 才会生成 component.js 文件？

**Comment by yoyo201626** [comment]
可以参考 dev 命令，` "dev": "pnpm build:entry && gulp themeConcat -w & pnpm -C examples/vue3 dev",`

> 好像只有 build:theme 才会生成 component.js 文件？

**Review by kagol — APPROVED** [review]

**Pull request merged**
