### PR TITLE
style(rich-text-editor): [rich-text-editor] css variable error

### PR DESCRIPTION
**Pull request by jevin98**
# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-vue/blob/dev/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A
#1363

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by kagol — COMMENTED** [review]
同级目录的 vars.less 中定义的主题变量名称也需要相应地修改

**Comment by jevin98** [comment]
> 同级目录的 vars.less 中定义的主题变量名称也需要相应地修改

为什么需要修改vars.less中定义的名称？ 只是index.less中变量名称写错了。

**Comment by wNing50** [comment]
"图片“下拉的样式也有问题，建议一块修改了

**Comment by kagol** [comment]
> > 同级目录的 vars.less 中定义的主题变量名称也需要相应地修改
> 
> 为什么需要修改vars.less中定义的名称？ 只是index.less中变量名称写错了。

哦，是我搞错了

**Review by gimmyhehe — DISMISSED** [review]

**Comment by kagol** [comment]
@Jevin0 麻烦解决下冲突

**Comment by jevin98** [comment]
@kagol resolve

**Review by zzcr — APPROVED** [review]

**Pull request merged**
