### PR TITLE
fix(dialog-box): Fix the problem that the dialog-box on the right cannot be scrolled

### PR DESCRIPTION
**Pull request by hiasky**
# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-vue/blob/dev/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #491 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by hiasky** [comment]
修复此问题时，发现footer插槽设置的是绝对定位，所以当文本过多时，底部footer也会覆盖文本，这部分是否需要优化

**Comment by GaoNeng-wWw** [comment]
> 修复此问题时，发现footer插槽设置的是绝对定位，所以当文本过多时，底部footer也会覆盖文本，这部分是否需要优化

是否同步修复一下？就在这个PR里

**Comment by hiasky** [comment]
> > 修复此问题时，发现footer插槽设置的是绝对定位，所以当文本过多时，底部footer也会覆盖文本，这部分是否需要优化
> 
> 是否同步修复一下？就在这个PR里

已同步修复

**Review by GaoNeng-wWw — APPROVED** [review]
LGTM

**Pull request merged**
