### PR TITLE
fix(dropdown): Invalid visible-arrow setting problem

### PR DESCRIPTION
**Pull request by chenguang1994**
# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-vue/blob/dev/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by GaoNeng-wWw** [comment]
可以贴一个效果图吗？

**Comment by chenguang1994** [comment]
@GaoNeng-wWw  修复#549 效果，默认情况下无箭头，设置visible-arrow后有箭头  
企业微信截图_16964827616197
企业微信截图_1696482777862
image

**Review by GaoNeng-wWw — APPROVED** [review]

**Comment by MomoPoppy** [comment]
visible-arrow 属于dropdownMenu的属性，是控制下拉菜单的下拉弹框是否显示箭头。默认不显示。
image
show-icon是 dropdown的属性，是控制下拉菜单的触发源的箭头是否显示，此属性为新增属性，会尽快补全官网api文档。
image

**Comment by kagol** [comment]
@chenguang1994 感谢你提交的PR，不过这应该不是一个问题。

- visible-arrow 是用来控制下拉菜单的箭头显隐，设置在 dropdown-menu 组件上，我看是生效的
- show-icon 是用来控制触发元素旁边那个箭头显隐，设置在dropdown组件上，由于是新增的功能，还没有更新到文档中

**Pull request closed without merging**
