### PR TITLE
fix(checkbox): icon position when checked

### PR DESCRIPTION
**Pull request by zuixinwang**
icon position not centered when checkbox is checked

# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/ui-vue/blob/main/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by zuixinwang** [comment]
@kagol this is my first time submitting PR to this project, is this PR suitable?😄

**Review by kagol — APPROVED** [review]

**Comment by kagol** [comment]
> @kagol this is my first time submitting PR to this project, is this PR suitable?😄

Awesome!🎉

**Comment by kagol** [comment]
Before:
image


After:
image

**Comment by kagol** [comment]
@all-contributors please add @zuixinwang for code

**Pull request merged**
