### PR TITLE
feat(rich-text-editor): [rich-text-editor] add image drag adjustment

### PR DESCRIPTION
**Pull request by HAOUEHF**
# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-vue/blob/dev/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: [1498](https://github.com/opentiny/tiny-vue/issues/1498)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by shenjunjian** [comment]
十分感谢提供新的插入图形拖拽大小的功能，基本可用。
但我实际测试遇到2个问题：
1、初始插入后，resize的大小固定为200*200 ， 简单拖动一下，就立即贴合图片了，不那么方便
image
 
2、插入多个图片，或多次插入同一张图片总不太顺手，有时候不行，不明白为什么。

可否再排查下原因 @HAOUEHF

**Comment by HAOUEHF** [comment]
@shenjunjian 没问题，我优化一下

**Comment by HAOUEHF** [comment]
@shenjunjian 图片初始化大小改为400，优化多张图片插入问题、图片拖拽最大宽度不能超出富文本编辑器的宽度，后续会继续参与富文本的开发优化

**Comment by HAOUEHF** [comment]
@all-contributors please add @星河 for code

**Comment by HAOUEHF** [comment]
@all-contributors please add @HAOUEHF  for code

**Review by zzcr — APPROVED** [review]

**Pull request merged**
