### PR TITLE
docs: fix typos

### PR DESCRIPTION
**Pull request by gweesin**
# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-vue/blob/dev/CONTRIBUTING.md)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

spell correctly

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **Bug Fixes**
  - Corrected typos and improved descriptions in commit message templates and demo files.
  
- **Documentation**
  - Enhanced English descriptions for input parameters in demos.
  - Updated documentation in both English and Chinese versions.

- **Refactor**
  - Restructured properties and interfaces in multiple chart demo files for improved organization and consistency.
  
These changes improve clarity, documentation quality, and code structure in demo files.

### CODE REVIEW

**Comment by kagol** [comment]
@gweesin 我看改了很多图表组件的api文档，这个只是修改格式，没有修改内容吧？

**Comment by kagol** [comment]
@gweesin 图表相关的修改只是修改代码格式，请单独提交一个PR，不要和修改错别字放在一个PR里

**Comment by gweesin** [comment]
> @gweesin 图表相关的修改只是修改代码格式，请单独提交一个PR，不要和修改错别字放在一个PR里

OK, wait for a moment

**Comment by gweesin** [comment]
> @gweesin 我看改了很多图表组件的api文档，这个只是修改格式，没有修改内容吧？

是的，目前回滚了 chart 相关的调整保证这个 pr 只调整拼写错误。

**Review by zzcr — APPROVED** [review]

**Pull request merged**
